highlighter: rouge

markdown: CommonMarkGhPages

kramdown:
  input: GFM
  math_engine: MathJax

commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

plugins:
  - jekyll-paginate
  # - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"
future: true

url: https://taegyunwoo.github.io # Required: replace this with your domain
name: MeCoMeGae # Required: will be displayed on every page's header
title: 매코매개 # Required: site's default title
shout: # Required: **TWO** lines, will be displayed on page's header.
  - 매일 코딩
  - 매일 개발
description: "개발자 블로그입니다." # Required

disqus:
  comments: true # Global toggle on/off disqus comment
  shortname: mecomegae # Required if you use disqus. Repalce with your disqus shortname here

google_analytics:
  id: "G-VDE33NGC7S" # Required if you use google analytics. Replace with your tracking id here

collections: # Define post series here
  CRUD_Web:
    output: false
  EMS:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: "post"