# SITE CONFIGURATION
# baseurl: "/Type-on-Strap"
baseurl: ""
url: "https://taegyunwoo.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Dev Blog                                    # site's title
description: "Taegyun's Development & Tech Blog"      # used by search engines
avatar: assets/img/me.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Taegyun's Development & Tech Blog  # Change Blog header text
header_feature_image: assets/img/header/triangular.jpeg
header_feature_image_responsive: true
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics: G-VDE33NGC7S                          # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light
permalink: /:categories/:title

# Comments
comments:
  disqus_shortname: mecomegae                           # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-toc]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github

words_per_minute: 200

# Site Author
author:
  name             : "Taegyun Woo"
  avatar           : "assets/img/me.png"
  bio              : "주니어 백엔드 개발자"
  email            : "dnxprbs@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:dnxprbs@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://taegyunwoo.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TaegyunWoo"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      #classes: wide
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: false
      toc: true
      toc_sticky: true